// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: micro02.proto

package microservice_02

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Waitsec       int32                  `protobuf:"varint,2,opt,name=waitsec,proto3" json:"waitsec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_micro02_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_micro02_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_micro02_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Data) GetWaitsec() int32 {
	if x != nil {
		return x.Waitsec
	}
	return 0
}

type Details struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Details) Reset() {
	*x = Details{}
	mi := &file_micro02_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Details) ProtoMessage() {}

func (x *Details) ProtoReflect() protoreflect.Message {
	mi := &file_micro02_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Details.ProtoReflect.Descriptor instead.
func (*Details) Descriptor() ([]byte, []int) {
	return file_micro02_proto_rawDescGZIP(), []int{1}
}

func (x *Details) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_micro02_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_micro02_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_micro02_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_micro02_proto protoreflect.FileDescriptor

var file_micro02_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x32, 0x22, 0x38, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x61, 0x69, 0x74,
	0x73, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x61, 0x69, 0x74, 0x73,
	0x65, 0x63, 0x22, 0x2e, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x23, 0x0a,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x30, 0x32, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x22, 0x1a, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x63,
	0x0a, 0x07, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x32, 0x12, 0x2b, 0x0a, 0x08, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x30, 0x31, 0x12, 0x0d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x32, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x1a, 0x10, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x32, 0x2e, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x30, 0x32, 0x12, 0x0d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x32, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x1a, 0x10, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x32, 0x2e, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x62, 0x77, 0x38, 0x30, 0x2d, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2d, 0x74,
	0x61, 0x73, 0x6b, 0x2d, 0x30, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d,
	0x30, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_micro02_proto_rawDescOnce sync.Once
	file_micro02_proto_rawDescData = file_micro02_proto_rawDesc
)

func file_micro02_proto_rawDescGZIP() []byte {
	file_micro02_proto_rawDescOnce.Do(func() {
		file_micro02_proto_rawDescData = protoimpl.X.CompressGZIP(file_micro02_proto_rawDescData)
	})
	return file_micro02_proto_rawDescData
}

var file_micro02_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_micro02_proto_goTypes = []any{
	(*Data)(nil),    // 0: micro02.Data
	(*Details)(nil), // 1: micro02.Details
	(*User)(nil),    // 2: micro02.User
}
var file_micro02_proto_depIdxs = []int32{
	2, // 0: micro02.Details.users:type_name -> micro02.User
	0, // 1: micro02.Micro02.Method01:input_type -> micro02.Data
	0, // 2: micro02.Micro02.Method02:input_type -> micro02.Data
	1, // 3: micro02.Micro02.Method01:output_type -> micro02.Details
	1, // 4: micro02.Micro02.Method02:output_type -> micro02.Details
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_micro02_proto_init() }
func file_micro02_proto_init() {
	if File_micro02_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_micro02_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_micro02_proto_goTypes,
		DependencyIndexes: file_micro02_proto_depIdxs,
		MessageInfos:      file_micro02_proto_msgTypes,
	}.Build()
	File_micro02_proto = out.File
	file_micro02_proto_rawDesc = nil
	file_micro02_proto_goTypes = nil
	file_micro02_proto_depIdxs = nil
}
