// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: micro01.proto

package microservice_01

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Details struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Details) Reset() {
	*x = Details{}
	mi := &file_micro01_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Details) ProtoMessage() {}

func (x *Details) ProtoReflect() protoreflect.Message {
	mi := &file_micro01_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Details.ProtoReflect.Descriptor instead.
func (*Details) Descriptor() ([]byte, []int) {
	return file_micro01_proto_rawDescGZIP(), []int{0}
}

func (x *Details) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Details) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Details) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_micro01_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_micro01_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_micro01_proto_rawDescGZIP(), []int{1}
}

type Get struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get) Reset() {
	*x = Get{}
	mi := &file_micro01_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get) ProtoMessage() {}

func (x *Get) ProtoReflect() protoreflect.Message {
	mi := &file_micro01_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get.ProtoReflect.Descriptor instead.
func (*Get) Descriptor() ([]byte, []int) {
	return file_micro01_proto_rawDescGZIP(), []int{2}
}

func (x *Get) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_micro01_proto protoreflect.FileDescriptor

var file_micro01_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x31, 0x22, 0x43, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x15, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x32, 0xc2, 0x01,
	0x0a, 0x07, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x31, 0x12, 0x2e, 0x0a, 0x0a, 0x55, 0x73, 0x65,
	0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30,
	0x31, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x0e, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x30, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2b, 0x0a, 0x09, 0x55, 0x73, 0x65,
	0x72, 0x46, 0x65, 0x74, 0x63, 0x68, 0x12, 0x0c, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x1a, 0x10, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x31, 0x2e, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x2e, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x31, 0x2e, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x0e, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x31,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2a, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x0c, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x1a, 0x0e, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x30, 0x31, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x77, 0x38, 0x30, 0x2d, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2d, 0x74, 0x61,
	0x73, 0x6b, 0x2d, 0x30, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x30,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_micro01_proto_rawDescOnce sync.Once
	file_micro01_proto_rawDescData = file_micro01_proto_rawDesc
)

func file_micro01_proto_rawDescGZIP() []byte {
	file_micro01_proto_rawDescOnce.Do(func() {
		file_micro01_proto_rawDescData = protoimpl.X.CompressGZIP(file_micro01_proto_rawDescData)
	})
	return file_micro01_proto_rawDescData
}

var file_micro01_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_micro01_proto_goTypes = []any{
	(*Details)(nil), // 0: micro01.Details
	(*Empty)(nil),   // 1: micro01.Empty
	(*Get)(nil),     // 2: micro01.Get
}
var file_micro01_proto_depIdxs = []int32{
	0, // 0: micro01.Micro01.UserCreate:input_type -> micro01.Details
	2, // 1: micro01.Micro01.UserFetch:input_type -> micro01.Get
	0, // 2: micro01.Micro01.UserUpdate:input_type -> micro01.Details
	2, // 3: micro01.Micro01.UserDelete:input_type -> micro01.Get
	1, // 4: micro01.Micro01.UserCreate:output_type -> micro01.Empty
	0, // 5: micro01.Micro01.UserFetch:output_type -> micro01.Details
	1, // 6: micro01.Micro01.UserUpdate:output_type -> micro01.Empty
	1, // 7: micro01.Micro01.UserDelete:output_type -> micro01.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_micro01_proto_init() }
func file_micro01_proto_init() {
	if File_micro01_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_micro01_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_micro01_proto_goTypes,
		DependencyIndexes: file_micro01_proto_depIdxs,
		MessageInfos:      file_micro01_proto_msgTypes,
	}.Build()
	File_micro01_proto = out.File
	file_micro01_proto_rawDesc = nil
	file_micro01_proto_goTypes = nil
	file_micro01_proto_depIdxs = nil
}
